./runAndTestConvergence.pl CosineHillRotateBC.xml -optionsFile np-1.dat
./runAndTestConvergence.pl CosineHillRotateBC.xml -optionsFile np-2.dat
./runAndTestConvergence.pl CosineHillRotateBC.xml -optionsFile np-4.dat
./runAndTestConvergence.pl CosineHillRotateBC-DualMesh.xml -optionsFile dual-np-1.dat
./runAndTestConvergence.pl CosineHillRotateBC-DualMesh.xml -optionsFile dual-np-2.dat
./runAndTestConvergence.pl CosineHillRotateBC-DualMesh.xml -optionsFile dual-np-4.dat
./runAndTestConvergence.pl HomogeneousNaturalBCs.xml -optionsFile np-1.dat
./runAndTestConvergence.pl HomogeneousNaturalBCs.xml -optionsFile np-2.dat
./runAndTestConvergence.pl HomogeneousNaturalBCs.xml -optionsFile np-4.dat
./runAndTestConvergence.pl HomogeneousNaturalBCs-DualMesh.xml -optionsFile dual-np-1.dat
./runAndTestConvergence.pl HomogeneousNaturalBCs-DualMesh.xml -optionsFile dual-np-2.dat
./runAndTestConvergence.pl HomogeneousNaturalBCs-DualMesh.xml -optionsFile dual-np-4.dat
./runAndTestConvergence.pl SteadyState1D-x.xml -optionsFile ss-0.5-np-1.dat
./runAndTestConvergence.pl SteadyState1D-x.xml -optionsFile ss-0.5-np-2.dat
./runAndTestConvergence.pl SteadyState1D-x.xml -optionsFile ss-0.5-np-4.dat
./runAndTestConvergence.pl SteadyState1D-x.xml -optionsFile np-1.dat
./runAndTestConvergence.pl SteadyState1D-x.xml -optionsFile np-2.dat
./runAndTestConvergence.pl SteadyState1D-x.xml -optionsFile np-4.dat
./runAndTestConvergence.pl SteadyState1D-y.xml -optionsFile np-1.dat
./runAndTestConvergence.pl SteadyState1D-y.xml -optionsFile np-2.dat
./runAndTestConvergence.pl SteadyState1D-y.xml -optionsFile np-4.dat
