import os
Import('env')

# Copy headers to our build directory.
incs = env['helpers']['copyHdrs'](env)
incs.append(env['helpers']['copyDefs'](env))

# Build our source files.
objs = env['helpers']['buildCSrcs'](env)

Return('objs')
