import os
Import('env')

# Execute subdirectory SConscripts.
SConscript('mpirecord/SConscript', exports='env')

# Copy headers to our build directory.
incs = env['helpers']['copyHdrs'](env)

# Build our source files.
objs = env['helpers']['buildCSrcs'](env)

Return('objs')
