##~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
##
## Copyright (C), 2003, Victorian Partnership for Advanced Computing (VPAC) Ltd, 110 Victoria Street, Melbourne, 3053, Australia.
##
## Authors:
##	Stevan M. Quenette, Senior Software Engineer, VPAC. (steve@vpac.org)
##	Patrick D. Sunter, Software Engineer, VPAC. (pds@vpac.org)
##	Luke J. Hodkinson, Computational Engineer, VPAC. (lhodkins@vpac.org)
##	Siew-Ching Tan, Software Engineer, VPAC. (siew@vpac.org)
##	Alan H. Lo, Computational Engineer, VPAC. (alan@vpac.org)
##	Raquibul Hassan, Computational Engineer, VPAC. (raq@vpac.org)
##
##  This library is free software; you can redistribute it and/or
##  modify it under the terms of the GNU Lesser General Public
##  License as published by the Free Software Foundation; either
##  version 2.1 of the License, or (at your option) any later version.
##
##  This library is distributed in the hope that it will be useful,
##  but WITHOUT ANY WARRANTY; without even the implied warranty of
##  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
##  Lesser General Public License for more details.
##
##  You should have received a copy of the GNU Lesser General Public
##  License along with this library; if not, write to the Free Software
##  Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
##
## $Id: Makefile.def 4160 2007-07-30 06:17:06Z DavidLee $
##
##~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

def_lib = StGermainDiscretisationUtils
def_inc = StGermain/Discretisation/Utils

def_srcs = \
	AllElementsVC.c \
	AllNodesVC.c \
	WallVC.c \
	InnerWallVC.c \
	CornerVC.c \
	MeshShapeVC.c \
	FrictionVC.c \
	SplitFrictionWallVC.c \
	DofLayout.c \
	RegularMeshUtils.c \
	Operator.c \
	FieldVariable.c \
	FieldVariable_Register.c \
	OperatorFieldVariable.c \
	DiscretisationContext.c \
	LinearRegression.c \
	TimeIntegrator.c \
	TimeIntegratee.c \
	ShapeAdvector.c \
	SobolGenerator.c \
	NewRemesher.c \
	Remesher.c \
	RegularRemesher.c \
	RegularRemesherCmpt.c \
	Init.c \
	Finalise.c
#	SemiRegDeform.c \
#	StripRemesher.c \
#	CellRemesher.c \

def_hdrs = \
	types.h \
	AllElementsVC.h \
	AllNodesVC.h \
	WallVC.h \
	InnerWallVC.h \
	CornerVC.h \
	MeshShapeVC.h \
	FrictionVC.h \
	SplitFrictionWallVC.h \
	DofLayout.h \
	RegularMeshUtils.h \
	Operator.h \
	FieldVariable.h \
	FieldVariable_Register.h \
	OperatorFieldVariable.h \
	DiscretisationContext.h \
	LinearRegression.h \
	TimeIntegrator.h \
	TimeIntegratee.h \
	ShapeAdvector.h \
	SobolGenerator.h \
	NewRemesher.def \
	NewRemesher.h \
	Remesher.h \
	RegularRemesher.def \
	RegularRemesher.h \
	RegularRemesherCmpt.h \
	Init.h \
	Finalise.h \
	Utils.h
#	SemiRegDeform.h \
#	StripRemesher.h \
#	CellRemesher.h \

def_objlists = 
