#undef INCLUDEPATH
#undef INCLUDEFILE
#undef _INCLUDECLASS
#undef INCLUDECLASS
#undef INCLUDEHDR
#undef INCLUDEPARENT

#undef CLASSTYPE

#undef PARENTINC
#undef PARENTOP
#undef CLASSOP

#undef _VIRTUALMETHOD
#undef VIRTUALMETHOD
#undef _VOIDVIRTUALMETHOD
#undef VOIDVIRTUALMETHOD
#undef _ABSTRACTMETHOD
#undef ABSTRACTMETHOD
#undef _VOIDABSTRACTMETHOD
#undef VOIDABSTRACTMETHOD
#undef OVERRIDE
#undef VOIDOVERRIDE
#undef _METHOD
#undef METHOD
