import os
Import('env objs')

# Execute subdirectory SConscripts.
objs += SConscript('src/SConscript', exports='env')

# Build libraries.
libs = env.Library('#build/lib/StgDomain', objs)
libs += env.LoadableModule('#build/lib/StgDomain', objs)
env.Install(os.path.join(env['prefix'], 'lib'), libs)

# Build tests.
SConscript('tests/SConscript', exports='env')

# Build toolbox.
SConscript('Toolbox/SConscript', exports='env')

Return('objs')
