import os
Import('env')

#
# Need to make a copy because SCons uses the environment.
# at it's final state, so StGermain ends up depending on
# StgDomain, etc.
#

env = env.Clone()

#
# Inside each project we will be accessing headers without the
# project name as a build_dir, so we need to let SCons know how to
# find those headers.
#

env.Append(CPPPATH=env['build_dir'] + '/include/json_parser')

hdrs = env.Install('include/json_parser/', Glob('include' + '/*.h'))

srcs = Glob('*.cxx')
objs = env.SharedObject(srcs)

l=env.StaticLibrary(env['build_dir'] + '/lib/json_parser', objs)
env.Install(env['prefix'] + '/lib', l)
