import os
Import('env objs')

# Execute subdirectory SConscripts.
objs += SConscript('src/SConscript', exports='env')

# Build libraries.
libs = env.Library('#build/lib/StGermain', objs)
libs += env.LoadableModule('#build/lib/StGermain', objs)
env.Install(os.path.join(env['prefix'], 'lib'), libs)

Return('objs')
