import os
Import('env')

# These guys go somewhere different than their source location.
hdrs = Split('Init.h Finalise.h StgDomain.h')
env.Install('#build/include/StgDomain', hdrs)

# Build our source files.
objs = env['helpers']['buildCSrcs'](env)

Return('objs')
